import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chairlift6</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hsl-logo.svg" />
      </Head>
      <main className={styles.main}>
          <h2 className={styles.titleMotion}>Chairlift6</h2>
          <svg className={styles.svg} xmlns="http://www.w3.org/2000/svg">
              <filter id="motion-blur-filter" filterUnits="userSpaceOnUse">
                  <feGaussianBlur stdDeviation="100 0"></feGaussianBlur>
              </filter>
          </svg>
          <span className={styles.textMotion} filter-content="S">WE ARE LAUNCHING SOON!</span>
        <p className={styles.description}>
          We are almost there! Stay turned for something amazing!!!
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://labs.haystack.asia/"
          target="_blank"
          rel="noopener noreferrer"
        >
            Made with ❤️By Haystack Labs Studios CO. LTD. <span className={'hidden sm:inline'}>  All rights reserved ©{new Date().getFullYear()} in Phnom Penh. </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
